RHSOLUTIONS/Controllers/FolhaController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PIMIVRH.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using PIMIVRH.Interfaces;

namespace PIMIVRH.Controllers
{
    public class FolhaController : Controller
    {
        public IActionResult Index()
        {
            FolhaModel folha = GerarFolha();
            return View(folha);
        }
        public FolhaModel GerarFolha()
        {
            conexaoSql Connectiostring = new conexaoSql();
            var conexaoSql = Connectiostring.ConnectionString;
            SqlConnection conexaoDB = new SqlConnection(conexaoSql);

            FolhaModel folha = new FolhaModel();

            var NCpf = HttpContext.Session.GetString("Cpf");
            conexaoDB.Open();

            string query = $"SELECT Nome, TelefoneFunc, CargoFunc, SalarioFunc, VAuxilioAlimentacao, VAuxilioRefeicao, Email, ValeTransporte "+
                           $"from FUNCIONARIO WHERE Cpf = '{NCpf}'";

            SqlCommand command = new SqlCommand(query, conexaoDB);
            SqlDataReader reader = command.ExecuteReader();

            while (reader.Read())
            {
                
                folha.Nome = reader.GetString(0);
                folha.Telefone = reader.GetString(1);
                folha.Cargo = reader.GetString(2);
                folha.Salario = reader.GetDouble(3);
                folha.VAuxilioAlim = reader.GetDouble(4);
                folha.VAuxilioRef = reader.GetDouble(5);
                folha.Email = reader.GetString(6);
                folha.ValeTransporte = reader.GetString(7);
                folha.Cpf = NCpf;

            }
            double descontoInss = CalculoInss(folha);
            double descontoIR = CalculoImpostoDeRenda(folha, descontoInss);
            double descontoVt = CalculoValeTransporte(folha);
            

            double salarioLiquido = folha.Salario - (descontoInss + descontoIR + descontoVt);
            ViewBag.salarioLiquido = $"{salarioLiquido}";
            conexaoDB.Close();

            return folha;

                
        }

        public double CalculoImpostoDeRenda(FolhaModel model, double Inss)
        {
            double x = model.Salario - Inss;
            if (x < 2112)
            {
                
                return x = 0;
            }
            else if (x > 2112 && x <= 2826.65)
            {
                
                x = (x * 7.5) / 100;
                x -= 158.40;
                return x;

            }
            else if (x > 2826.65 && x <= 3751.05)
            {
                
                x = (x * 15) / 100;
                x -= 370.40;
                return x;
            }
            else if (x > 3751.05 && x <= 4664.68)
            {
                
                x = (x * 22.5) / 100;
                x -= 651.73;
                return x;
            }
            else if (x > 4664.68)
            {
                
                x = (x * 27.5) / 100;
                x -= 884.96;
                return x;
            }
            else
            { return 0; }
        }

        public double CalculoInss(FolhaModel model)
        {
            try
            {
                double x = model.Salario;
                if (x <= 1320)
                {
                    
                    x = (x * 7) / 100;
                    return x;
                }
                else if (x >= 1321 && x <= 2571)
                {
                    
                    x -= 1320;
                    x = (x * 9) / 100;
                    x += 99;
                    return x;
                }
                else if (x >= 2572 && x <= 3856)
                {
                    
                    x -= 2571.29;
                    x = (x * 12) / 100;
                    x += 99;
                    x += 112.62;
                    return x;
                }
                else if (x >= 3857 && x <= 7507.49)
                {
                    
                    x -= 3856.94;
                    x = (x * 14) / 100;
                    x += 99;
                    x += 112.62;
                    x += 154.28;
                    return x;
                }
                else if (x > 7507.49)
                {
                    
                    return x = 876.97;
                }
                else
                {
                    return 0;
                }

            }
            catch (Exception)
            {
                throw;
            }
        }

        public double CalculoValeTransporte(FolhaModel model)
        {
            if(model.ValeTransporte == "S")
            {
                var descontoVT = model.Salario * 0.06;
                return descontoVT;
            }
            return 0.0;
            
        }
    }
}

RHSOLUTIONS/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PIMIVRH.Interfaces;
using PIMIVRH.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using PIMIVRH.Interfaces;

namespace PIMIVRH.Controllers
{
    public class LoginController : Controller
    {

        


        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult ValidaUsuario(LoginModel login)
        {
            if (Validacao(login))
            {
                return RedirectToAction("Index", "Home");
            } 
            return View("Index");
        }
        protected bool Validacao(LoginModel login)
        {
            LoginModel loginModel = new LoginModel();

            conexaoSql Connectiostring = new conexaoSql();
            var conexaoSql = Connectiostring.ConnectionString;
            SqlConnection conexaoDB = new SqlConnection(conexaoSql);

            conexaoDB.Open();

            if(login.Funcional == null  || login.Senha == null)
            {
                TempData["MensagemErro"] = "Não foi possivel fazer o login funcional ou senha incorretos";
                return false;
            }
            if (login.Funcional == " " || login.Senha == " ")
            {
                TempData["MensagemErro"] = "Não foi possivel fazer o login funcional ou senha incorretos";
                return false;
            }

            if (!login.Funcional.StartsWith("033"))
            {
                TempData["MensagemErro"] = "não foi possivel fazer o login";
                return false;
            }
            string query = $"SELECT Funcional, Senha FROM FUNCIONARIO WHERE Funcional = '{login.Funcional}' AND Senha = '{login.Senha}'";
            SqlCommand command = new SqlCommand(query, conexaoDB);
            SqlDataReader reader = command.ExecuteReader();
            if (!reader.Read())
            {
                
                TempData["MensagemErro"] = "Não foi possivel fazer o login funcional ou senha incorretos";
                return false;
                
            }
            else
            {
                loginModel.Funcional = reader.GetString(0);
                HttpContext.Session.SetString("Funcional", loginModel.Funcional);
                
                
            return true;
            }
        }
    }
}

RHSOLUTIONS/Controllers/PontoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PIMIVRH.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using PIMIVRH.Interfaces;

namespace PIMIVRH.Controllers
{
    public class PontoController : Controller
    {
        public int TotalHorasTrabalhadas { get; set; }
        public int HorasFaltantes { get; set; }
        public int HorasACompensar { get; set; }

        public IActionResult Index()
        {
            
            List<PontoModel> listaPonto = ListarPontoEletronico();
            return View(listaPonto);
        }

        public List<PontoModel> ListarPontoEletronico()
        {
            conexaoSql Connectiostring = new conexaoSql();
            var conexaoSql = Connectiostring.ConnectionString;
            SqlConnection conexaoDB = new SqlConnection(conexaoSql);

            List<PontoModel> lista = new List<PontoModel>();

            var NCpf = HttpContext.Session.GetString("Cpf");

            conexaoDB.Open();

            string query = $"SELECT * FROM PONTO WHERE Cpf = '{NCpf}'";
            SqlCommand command = new SqlCommand(query, conexaoDB);
            SqlDataReader reader = command.ExecuteReader();
            while (reader.Read())
            {
                PontoModel ponto = new PontoModel();

                ponto.PrimeiraBatida = reader.IsDBNull(0) ? TimeSpan.Zero: reader.GetTimeSpan(0);
                ponto.SegundaBatida = reader.IsDBNull(1) ? TimeSpan.Zero : reader.GetTimeSpan(1);
                ponto.TerceiraBatida = reader.IsDBNull(2) ? TimeSpan.Zero : reader.GetTimeSpan(2);
                ponto.QuartaBatida = reader.IsDBNull(3) ? TimeSpan.Zero : reader.GetTimeSpan(3);
                ponto.HorasTrabalhadas = reader.IsDBNull(4) ? TimeSpan.Zero : reader.GetTimeSpan(4);
                ponto.Cpf = reader.GetString(5);
                ponto.Dia = reader.GetDateTime(6).Date;

                lista.Add(ponto);
            }

            conexaoDB.Close();

            CalculoHoras(lista);

            return lista;
        }

        public void CalculoHoras(List<PontoModel> lista)
        {
            var horasReportar = 0.0;
            var horasTotais = TimeSpan.Zero;
            var horasNoMes = 176.00;
            foreach (var item in lista)
            {
                var horasDia = item.HorasTrabalhadas;
                horasTotais = horasTotais + horasDia;
            }
            horasReportar = horasNoMes - horasTotais.TotalHours;
            horasReportar = horasReportar + 8;

            HttpContext.Session.SetString("horasTotais", horasReportar.ToString("N2"));

            ViewBag.reportar = horasReportar.ToString("N2");
            ViewBag.data = $"{horasTotais.TotalHours}:{horasTotais.Minutes}";
        }

        public IActionResult BaterPonto()
        {
            conexaoSql Connectiostring = new conexaoSql();
            var conexaoSql = Connectiostring.ConnectionString;
            SqlConnection conexaoDB = new SqlConnection(conexaoSql);
            PontoModel ponto = new PontoModel();

            List<PontoModel> lista = new List<PontoModel>();

            var NCpf = HttpContext.Session.GetString("Cpf");

            DateTime dataHora = DateTime.Now;

            string HorasFormatada = dataHora.ToString("T");
            string dataFormatada = dataHora.ToString("dd/MM/yyyy"); 

            conexaoDB.Open();

            string query = "UPDATE PONTO " +
                            $"SET QuartaBatida = '{HorasFormatada}' " +
                            $"WHERE Cpf = '{NCpf}' AND Dia = '{dataFormatada}' AND PrimeiraBatida is not null AND SegundaBatida is not null AND TerceiraBatida is not null " +
                            "UPDATE PONTO " +
                            $"SET TerceiraBatida = '{HorasFormatada}' " +
                            $"WHERE Cpf = '{NCpf}' AND Dia = '{dataFormatada}' AND PrimeiraBatida is not null AND SegundaBatida is not null " +
                            "UPDATE PONTO " +
                            $"SET SegundaBatida = '{HorasFormatada}' " +
                            $"WHERE Cpf = '{NCpf}' AND Dia = '{dataFormatada}' AND PrimeiraBatida is not null " +
                            $"IF NOT EXISTS(SELECT 1 FROM PONTO WHERE Cpf = '{NCpf}' AND Dia = '{dataFormatada}' AND PrimeiraBatida is not null) " +
                            "BEGIN " +
                            "INSERT INTO PONTO(Cpf, Dia, PrimeiraBatida) " +
                            $"Values('{NCpf}', '{dataFormatada}', '{HorasFormatada}') " +
                            "END " +
                            $"SELECT * FROM PONTO WHERE Cpf = '{NCpf}' AND Dia = '{dataFormatada}'";

            SqlCommand command = new SqlCommand(query, conexaoDB);

            SqlDataReader reader = command.ExecuteReader();
            while (reader.Read())
            {
                ponto.PrimeiraBatida = reader.IsDBNull(0) ? TimeSpan.Zero : reader.GetTimeSpan(0);
                ponto.SegundaBatida = reader.IsDBNull(1) ? TimeSpan.Zero : reader.GetTimeSpan(1);
                ponto.TerceiraBatida = reader.IsDBNull(2) ? TimeSpan.Zero : reader.GetTimeSpan(2);
                ponto.QuartaBatida = reader.IsDBNull(3) ? TimeSpan.Zero : reader.GetTimeSpan(3);
                ponto.HorasTrabalhadas = reader.IsDBNull(4) ? TimeSpan.Zero : reader.GetTimeSpan(4);
                ponto.Cpf = reader.GetString(5);
                ponto.Dia = reader.GetDateTime(6).Date;

                lista.Add(ponto);
            }

            var horastrabalhadas = CalcularHorasTrabalhadas(lista);

            iserirHoras(dataFormatada, horastrabalhadas);

            conexaoDB.Close();

            

            return RedirectToAction("Index", "Home");

           

        }

        public void iserirHoras(string dataFormatada, TimeSpan horasTrabalhadas)
        {
            conexaoSql Connectiostring = new conexaoSql();
            var conexaoSql = Connectiostring.ConnectionString;
            SqlConnection conexaoDB = new SqlConnection(conexaoSql);

            conexaoDB.Open();

            var NCpf = HttpContext.Session.GetString("Cpf");

            string query = "UPDATE PONTO " +
                                        $"SET HorasTrabalhadas = '{horasTrabalhadas}' " +
                                        $"WHERE cpf = '{NCpf}' AND dia = '{dataFormatada}'";

            SqlCommand command = new SqlCommand(query, conexaoDB);
            SqlDataReader reader = command.ExecuteReader();
        }

        private TimeSpan CalcularHorasTrabalhadas(List<PontoModel> lista)
        {
            TimeSpan horaTrabalhadaTotal = TimeSpan.Zero;

            foreach (var item in lista)
            {

                if (item.SegundaBatida != TimeSpan.Zero && item.QuartaBatida != TimeSpan.Zero)
                {
                    var horasPrimeiroPeriodo = item.SegundaBatida - item.PrimeiraBatida;
                    var horasSegundoPeriodo = item.QuartaBatida - item.TerceiraBatida;
                    horaTrabalhadaTotal += horasPrimeiroPeriodo + horasSegundoPeriodo;
                }
                    
            }
            return horaTrabalhadaTotal;


        }
    }
}

RHSOLUTIONS/Views/Folha/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model FolhaModel
<body style="margin-bottom: 0%">
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-2 bg-dark min-vh-100">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline ">Bem vindo funcionario</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link align-middle px-0">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                            </a>
                        </li>
                        <li>
                            <a data-bs-toggle="collapse" asp-controller="Ponto" asp-action="Index" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-clock"></i> <span class="ms-1 d-none d-sm-inline">Ponto eletrônico</span>
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Folha" asp-action="Index" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Folhas de pagamento</span>
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Ferias" asp-action="Index" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-airplane"></i> <span class="ms-1 d-none d-sm-inline">Férias</span>
                            </a>
                        </li>
                        <li>
                            <a data-bs-toggle="collapse" asp-controller="Login" asp-action="Index" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-box-arrow-in-left"></i> <span class="ms-1 d-none d-sm-inline">Sair</span>
                            </a>
                        </li>
                    </ul>
                    <hr>
                </div>
            </div>
            <div class="container">
                <div class="row border Regular shadow" style="margin-top:20px; margin-bottom:20px">
                    <a>
                        <i class="fs-4 bi-table" style="font-size:30px; margin-right: 20px; margin-left:10px"></i><span style="font-size:30px">Folha de pagamento</span>
                    </a>
                </div>

                <form class="border">
                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Nome</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="@Model.Nome">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="@Model.Email">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Cpf</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="@Model.Cpf">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Telefone</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="@Model.Telefone">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Cargo</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="@Model.Cargo">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Valor auxilio alimentação</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="@Model.VAuxilioAlim">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Valor auxilio refeição</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="@Model.VAuxilioRef">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Vale transporte</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="@Model.ValeTransporte">
                        </div>
                    </div>
                    @*<div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Horas</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="">
                        </div>
                    </div>*@
                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Salário bruto</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="@Model.Salario">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Salário Liquido</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="@ViewBag.salarioLiquido">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

RHSOLUTIONS/Views/Folha/View.cshtml
@{
    ViewData["Title"] = "View";
    Layout = "Index";
}
<div class="container">
    <div class="row border Regular shadow" style="margin-top:20px; margin-bottom:20px">
        <a>
            <i class="fs-4 bi-file-earmark-post" style="font-size:30px; margin-right: 20px; margin-left:10px"></i><span style="font-size:30px">Folha de pagamento</span>
        </a>
    </div>
</div>