RHSOLUTIONS/Controllers/AlterarController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PIMIVRH.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using PIMIVRH.Interfaces;

namespace PIMIVRH.Controllers
{
    public class AlterarController : Controller
    {
        public IActionResult Index()
        {
            var modelo = listarHome();
            return View(modelo);
        }

        public FuncionarioModel listarHome()
        {
            conexaoSql Connectiostring = new conexaoSql();
            var conexaoSql = Connectiostring.ConnectionString;
            SqlConnection conexaoDB = new SqlConnection(conexaoSql);
            FuncionarioModel Home = new FuncionarioModel();


            var NFuncional = HttpContext.Session.GetString("Funcional");



            conexaoDB.Open();

            string query = $"SELECT * FROM FUNCIONARIO AS A FULL JOIN ENDERECOFUNC AS B ON A.Cpf = B.Cpf WHERE Funcional = '{NFuncional}'";
            SqlCommand command = new SqlCommand(query, conexaoDB);
            SqlDataReader reader = command.ExecuteReader();
            while (reader.Read())
            {
                Home.Nome = reader.GetString(1);
                Home.Telefone = reader.GetString(2);
                Home.CargoFunc = reader.GetString(3);
                Home.SalarioFunc = reader.GetDouble(4);
                Home.VAuxilioAlimentacao = reader.GetDouble(6);
                Home.VAuxilioRefeicao = reader.GetDouble(7);
                Home.Email = reader.GetString(9);
                Home.Endereco = reader.GetString(13);
                Home.Numero = reader.GetInt32(14);
                Home.Complemento = reader.GetString(15);
                Home.Cidade = reader.GetString(16);
                Home.Cep = reader.GetString(18);

            }

            return Home;
        }

        public IActionResult AlterarDados(FuncionarioModel Modelo)
        {
            conexaoSql Connectiostring = new conexaoSql();
            var conexaoSql = Connectiostring.ConnectionString;
            SqlConnection conexaoDB = new SqlConnection(conexaoSql);
            FuncionarioModel Home = new FuncionarioModel();


            var NFuncional = HttpContext.Session.GetString("Funcional");
            var NCpf = HttpContext.Session.GetString("Cpf");


            conexaoDB.Open();

            string query = "UPDATE FUNCIONARIO" +
                " SET " +
                $"Nome = '{Modelo.Nome}'," +
                $"TelefoneFunc = '{Modelo.Telefone}'," +
                $"CargoFunc = '{Modelo.CargoFunc}'," +
                $"SalarioFunc = {Modelo.SalarioFunc}," +
                $"Funcional = '{NFuncional}'," +
                $"VAuxilioAlimentacao = {Modelo.VAuxilioAlimentacao}," +
                $"VAuxilioRefeicao = {Modelo.VAuxilioRefeicao}," +
                $"Email = '{Modelo.Email}'" +
                $"WHERE Cpf = '{NCpf}' ";

            SqlCommand command = new SqlCommand(query, conexaoDB);
            SqlDataReader reader = command.ExecuteReader();

            conexaoDB.Close();

            AlterarEndereco(Modelo);

            return RedirectToAction("Index", "Home");
        }
        private void AlterarEndereco(FuncionarioModel modelo)
        {
            conexaoSql Connectiostring = new conexaoSql();
            var conexaoSql = Connectiostring.ConnectionString;
            SqlConnection conexaoDB = new SqlConnection(conexaoSql);
            FuncionarioModel Home = new FuncionarioModel();


            var NFuncional = HttpContext.Session.GetString("Funcional");
            var NCpf = HttpContext.Session.GetString("Cpf");


            conexaoDB.Open();

            string query = "UPDATE ENDERECOFUNC " +
                $"SET Endereco = '{modelo.Endereco}'," +
                $"Numero = {modelo.Numero}," +
                $"Complemento = '{modelo.Complemento}'," +
                $"Cidade = '{modelo.Cidade}'," +
                $"Cpf = '{NCpf}'," +
                $"Cep = '{modelo.Cep}'" +
                $"WHERE Cpf = '{NCpf}'";

            SqlCommand command = new SqlCommand(query, conexaoDB);
            SqlDataReader reader = command.ExecuteReader();

            conexaoDB.Close();
        }
    }
}

RHSOLUTIONS/Controllers/FolhaController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PIMIVRH.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using PIMIVRH.Interfaces;

namespace PIMIVRH.Controllers
{
    public class FolhaController : Controller
    {
        public IActionResult Index()
        {
            FolhaModel folha = GerarFolha();
            return View(folha);
        }
        public FolhaModel GerarFolha()
        {
            conexaoSql Connectiostring = new conexaoSql();
            var conexaoSql = Connectiostring.ConnectionString;
            SqlConnection conexaoDB = new SqlConnection(conexaoSql);

            FolhaModel folha = new FolhaModel();

            var NCpf = HttpContext.Session.GetString("Cpf");
            conexaoDB.Open();

            string query = $"SELECT Nome, TelefoneFunc, CargoFunc, SalarioFunc, VAuxilioAlimentacao, VAuxilioRefeicao, Email, ValeTransporte "+
                           $"from FUNCIONARIO WHERE Cpf = '{NCpf}'";

            SqlCommand command = new SqlCommand(query, conexaoDB);
            SqlDataReader reader = command.ExecuteReader();

            while (reader.Read())
            {
                
                folha.Nome = reader.GetString(0);
                folha.Telefone = reader.GetString(1);
                folha.Cargo = reader.GetString(2);
                folha.Salario = reader.GetDouble(3);
                folha.VAuxilioAlim = reader.GetDouble(4);
                folha.VAuxilioRef = reader.GetDouble(5);
                folha.Email = reader.GetString(6);
                folha.ValeTransporte = reader.GetString(7);
                folha.Cpf = NCpf;

            }
            double descontoInss = CalculoInss(folha);
            double descontoIR = CalculoImpostoDeRenda(folha, descontoInss);
            double descontoVt = CalculoValeTransporte(folha);
            

            double salarioLiquido = folha.Salario - (descontoInss + descontoIR + descontoVt);
            ViewBag.salarioLiquido = $"{salarioLiquido}";
            conexaoDB.Close();

            return folha;

                
        }

        public double CalculoImpostoDeRenda(FolhaModel model, double Inss)
        {
            double x = model.Salario - Inss;
            if (x < 2112)
            {
                
                return x = 0;
            }
            else if (x > 2112 && x <= 2826.65)
            {
                
                x = (x * 7.5) / 100;
                x -= 158.40;
                return x;

            }
            else if (x > 2826.65 && x <= 3751.05)
            {
                
                x = (x * 15) / 100;
                x -= 370.40;
                return x;
            }
            else if (x > 3751.05 && x <= 4664.68)
            {
                
                x = (x * 22.5) / 100;
                x -= 651.73;
                return x;
            }
            else if (x > 4664.68)
            {
                
                x = (x * 27.5) / 100;
                x -= 884.96;
                return x;
            }
            else
            { return 0; }
        }

        public double CalculoInss(FolhaModel model)
        {
            try
            {
                double x = model.Salario;
                if (x <= 1320)
                {
                    
                    x = (x * 7) / 100;
                    return x;
                }
                else if (x >= 1321 && x <= 2571)
                {
                    
                    x -= 1320;
                    x = (x * 9) / 100;
                    x += 99;
                    return x;
                }
                else if (x >= 2572 && x <= 3856)
                {
                    
                    x -= 2571.29;
                    x = (x * 12) / 100;
                    x += 99;
                    x += 112.62;
                    return x;
                }
                else if (x >= 3857 && x <= 7507.49)
                {
                    
                    x -= 3856.94;
                    x = (x * 14) / 100;
                    x += 99;
                    x += 112.62;
                    x += 154.28;
                    return x;
                }
                else if (x > 7507.49)
                {
                    
                    return x = 876.97;
                }
                else
                {
                    return 0;
                }

            }
            catch (Exception)
            {
                throw;
            }
        }

        public double CalculoValeTransporte(FolhaModel model)
        {
            if(model.ValeTransporte == "S")
            {
                var descontoVT = model.Salario * 0.06;
                return descontoVT;
            }
            return 0.0;
            
        }
    }
}

RHSOLUTIONS/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PIMIVRH.Interfaces;
using PIMIVRH.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using PIMIVRH.Interfaces;

namespace PIMIVRH.Controllers
{
    public class LoginController : Controller
    {

        


        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult ValidaUsuario(LoginModel login)
        {
            if (Validacao(login))
            {
                return RedirectToAction("Index", "Home");
            } 
            return View("Index");
        }
        protected bool Validacao(LoginModel login)
        {
            LoginModel loginModel = new LoginModel();

            conexaoSql Connectiostring = new conexaoSql();
            var conexaoSql = Connectiostring.ConnectionString;
            SqlConnection conexaoDB = new SqlConnection(conexaoSql);

            conexaoDB.Open();

            if(login.Funcional == null  || login.Senha == null)
            {
                TempData["MensagemErro"] = "Não foi possivel fazer o login funcional ou senha incorretos";
                return false;
            }
            if (login.Funcional == " " || login.Senha == " ")
            {
                TempData["MensagemErro"] = "Não foi possivel fazer o login funcional ou senha incorretos";
                return false;
            }

            if (!login.Funcional.StartsWith("033"))
            {
                TempData["MensagemErro"] = "não foi possivel fazer o login";
                return false;
            }
            string query = $"SELECT Funcional, Senha FROM FUNCIONARIO WHERE Funcional = '{login.Funcional}' AND Senha = '{login.Senha}'";
            SqlCommand command = new SqlCommand(query, conexaoDB);
            SqlDataReader reader = command.ExecuteReader();
            if (!reader.Read())
            {
                
                TempData["MensagemErro"] = "Não foi possivel fazer o login funcional ou senha incorretos";
                return false;
                
            }
            else
            {
                loginModel.Funcional = reader.GetString(0);
                HttpContext.Session.SetString("Funcional", loginModel.Funcional);
                
                
            return true;
            }
        }
    }
}

RHSOLUTIONS/Views/Alterar/Index.cshtml
@model FuncionarioModel
@{
    ViewData["Title"] = "Index";
}

<body style="margin-bottom: 0%">
        <div class="container-fluid">
            <div class="row flex-nowrap">
                <div class="col-auto col-md-2 bg-dark min-vh-100">
                    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                        <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">

                            <span class="fs-5 d-none d-sm-inline ">Bem Vindo </span>

                        </a>
                        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                            <li class="nav-item">
                                <a class="nav-link align-middle px-0" asp-controller="Home" asp-action="Index">
                                    <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                                </a>
                            </li>
                            <li>
                                <a data-bs-toggle="collapse" asp-controller="Ponto" asp-action="Index" class="nav-link px-0 align-middle">
                                    <i class="fs-4 bi-clock"></i> <span class="ms-1 d-none d-sm-inline">Ponto eletrônico</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Folha" asp-action="Index" class="nav-link px-0 align-middle">
                                    <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Folhas de pagamento</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Ferias" asp-action="Index" class="nav-link px-0 align-middle">
                                    <i class="fs-4 bi-airplane"></i> <span class="ms-1 d-none d-sm-inline">Férias</span>
                                </a>
                            </li>
                            <li>
                                <a data-bs-toggle="collapse" asp-controller="Login" asp-action="Index" class="nav-link px-0 align-middle">
                                    <i class="fs-4 bi-box-arrow-in-left"></i> <span class="ms-1 d-none d-sm-inline">Sair</span>
                                </a>
                            </li>
                        </ul>
                        <hr>
                    </div>
                </div>
                <div>
                </div>
                <div class="container">
                    <div class="row border Regular shadow" style="margin-top:20px; margin-bottom:20px">
                        <a>
                            <i class="fs-4 bi-file-person-fill" style="font-size:30px; margin-right: 20px; margin-left:10px"></i><span style="font-size:30px">Alteração de dados pessoais</span>
                        </a>
                    </div>
                    <form>
                        <div class="form-group">
                            <label>Nome</label>
                            <input type="text" class="form-control" asp-for="Nome" aria-describedby="emailHelp" placeholder="Nome">
                        </div>
                        <div class="form-group">
                            <label>Telefone</label>
                            <input type="tel" class="form-control" asp-for="Telefone" placeholder="11 00000-0000">
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="email" class="form-control" asp-for="Email" placeholder="name@example.com">
                        </div>
                        <div class="form-group">
                            <label>Cargo</label>
                            <input type="text" class="form-control" asp-for="CargoFunc" placeholder="Ex: Gerente">
                        </div>
                        <div class="form-group">
                            <label>Endereço</label>
                            <input type="text" class="form-control" asp-for="Endereco" placeholder="Ex: Rua das flores">
                        </div>
                        <div class="form-group">
                            <label>Numero</label>
                            <input type="number" class="form-control" asp-for="Numero" placeholder="Ex: 123">
                        </div>
                        <div class="form-group">
                            <label>Complemento</label>
                            <input type="text" class="form-control" asp-for="Complemento" placeholder="Ex: apto 2">
                        </div>
                        <div class="form-group">
                            <label>Cidade</label>
                            <input type="text" class="form-control" asp-for="Cidade" placeholder="Ex: São Paulo">
                        </div>
                        <div class="form-group">
                            <label>Cep</label>
                            <input type="text" class="form-control" asp-for="Cep" placeholder="Ex: 00000-000">
                        </div>
                        <button type="submit" asp-controller="Alterar" asp-action="AlterarDados" class="btn btn-primary">Fazer Alteração</button>
                    </form>
                </div>
            </div>
        </div>
</body>